# Generated by Django 4.2.2 on 2023-06-30 23:58

import django.core.validators
from django.db import migrations, models

import account.services


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="img",
            field=models.ImageField(
                blank=True,
                default=account.services.get_default_user_img_path,
                null=True,
                upload_to=account.services.get_custom_user_img_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg"]
                    ),
                    account.services.validate_size_image,
                ],
            ),
        ),
    ]
