# Generated by Django 4.2.2 on 2023-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
