version: '3.9'
services:
  nginx:
    container_name: 'nginx'
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - '1337:80'
    depends_on:
      - web

  web:
    container_name: 'web'
    build:
      context: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    container_name: 'database'
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'

  adminer:
    container_name: 'adminer'
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

volumes:
  postgres_data:
  static_volume:
  media_volume: