name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: --exclude=".git" --exclude=".github" --exclude=".env" --exclude="media" --exclude="staticfiles" --exclude="ssl" --exclude="db.json" -avzr --delete
          path: ./
          remote_path: /opt/DjangoBlog
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: build & start project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /opt/DjangoBlog && docker-compose down && docker-compose up -d --build
